/**
 * Automatically maps technology skill names to their official vector SVG logos
 * using Simple Icons CDN.
 */
export const getSkillLogoUrl = (skillName) => {
  if (!skillName) return null;
  const name = skillName.toLowerCase().trim();

  // Special slug mappings for SimpleIcons CDN
  const slugMap = {
    'next.js': 'nextdotjs',
    'nextjs': 'nextdotjs',
    'next': 'nextdotjs',
    'react': 'react',
    'react.js': 'react',
    'reactjs': 'react',
    'typescript': 'typescript',
    'ts': 'typescript',
    'javascript': 'javascript',
    'js': 'javascript',
    'tailwind': 'tailwindcss',
    'tailwind css': 'tailwindcss',
    'tailwindcss': 'tailwindcss',
    'node.js': 'nodedotjs',
    'nodejs': 'nodedotjs',
    'node': 'nodedotjs',
    'express': 'express',
    'express.js': 'express',
    'expressjs': 'express',
    'html5': 'html5',
    'html': 'html5',
    'css3': 'css3',
    'css': 'css3',
    'git': 'git',
    'github': 'github',
    'vite': 'vite',
    'vs code': 'visualstudiocode',
    'vscode': 'visualstudiocode',
    'figma': 'figma',
    'vercel': 'vercel',
    'python': 'python',
    'fastapi': 'fastapi',
    'django': 'django',
    'docker': 'docker',
    'kubernetes': 'kubernetes',
    'postgresql': 'postgresql',
    'postgres': 'postgresql',
    'mongodb': 'mongodb',
    'mongo': 'mongodb',
    'redis': 'redis',
    'vue': 'vuedotjs',
    'vue.js': 'vuedotjs',
    'vuejs': 'vuedotjs',
    'angular': 'angular',
    'svelte': 'svelte',
    'svelkit': 'svelte',
    'bootstrap': 'bootstrap',
    'sass': 'sass',
    'scss': 'sass',
    'graphql': 'graphql',
    'aws': 'amazonwebservices',
    'gcp': 'googlecloud',
    'firebase': 'firebase',
    'supabase': 'supabase',
    'go': 'go',
    'golang': 'go',
    'rust': 'rust',
    'java': 'openjdk',
    'kotlin': 'kotlin',
    'swift': 'swift',
    'php': 'php',
    'laravel': 'laravel',
    'mysql': 'mysql',
    'c#': 'csharp',
    'c++': 'cplusplus',
    'flutter': 'flutter',
    'dart': 'dart',
    'android': 'android',
    'ios': 'apple',
    'shadcn': 'shadcnui',
    'shadcn/ui': 'shadcnui',
    'prisma': 'prisma',
    'trpc': 'trpc',
    'stripe': 'stripe',
    'wordpress': 'wordpress',
    'postman': 'postman',
    'jest': 'jest',
    'cypress': 'cypress',
    'playwright': 'playwright',
    'redux': 'redux',
    'three.js': 'threedotjs',
    'threejs': 'threedotjs'
  };

  const slug = slugMap[name] || name.replace(/[^a-z0-9]/g, '');
  if (!slug) return null;
  return `https://cdn.simpleicons.org/${slug}/ffffff`;
};
